# Game start delays
game_wait: 60 #s
game_add_wait: 20 #s
game_add_wait_limit: 2

# Rate limits
wait_ping: 60 * 2 #s
wait_stats: 60 * 1/2 #s

# Durations
length_night: 60 * 2 #s
length_day: 60 * 15 #s

# Warnings
warn_night: 60 * 1.5 #s
warn_day: 60 * 13 #s

# Capacities
min_players: 4
max_players: 30

# Grace periods
grace_part: 7 #s
grace_quit: 60 * 1/2 #s

roles: 
#########################################################################################################
## PLAYERS:    SEER    WOLF   CURSED   DRUNK  HARLOT  TRAITOR  GUNNER   CROW  ANGEL  DETECTIVE  GHOST  ##
#########################################################################################################
      4   :  [   1   ,   1   ,   0   ,   0   ,   0   ,   0   ,   0   ,   0   ,   0   ,   0   ,   1   ] ##
      6   :  [   1   ,   1   ,   1   ,   1   ,   0   ,   0   ,   0   ,   0   ,   0   ,   0   ,   1   ] ##
      8   :  [   1   ,   2   ,   1   ,   1   ,   1   ,   0   ,   0   ,   0   ,   0   ,   0   ,   1   ] ##
      10  :  [   1   ,   2   ,   1   ,   1   ,   1   ,   1   ,   1   ,   0   ,   0   ,   0   ,   1   ] ##
      12  :  [   1   ,   2   ,   1   ,   1   ,   1   ,   1   ,   1   ,   1   ,   0   ,   1   ,   1   ] ##
      15  :  [   1   ,   2   ,   1   ,   1   ,   1   ,   2   ,   1   ,   1   ,   0   ,   1   ,   1   ] ##
      17  :  [   1   ,   2   ,   1   ,   1   ,   1   ,   2   ,   1   ,   1   ,   1   ,   1   ,   1   ] ##
      22  :  [   1   ,   3   ,   1   ,   1   ,   1   ,   2   ,   1   ,   1   ,   1   ,   1   ,   1   ] ##
      25  :  [   1   ,   3   ,   1   ,   1   ,   1   ,   2   ,   1   ,   1   ,   1   ,   1   ,   1   ] ##
      29  :  [   1   ,   4   ,   1   ,   1   ,   1   ,   2   ,   1   ,   1   ,   1   ,   1   ,   1   ] ##
#########################################################################################################

shots_multiplier: .12 # ceil( shots_multiplier * count(players) )

# Chances: syntax: 1/7 = [1,7]

#                   HIT    MISS   SUICIDE
gun_shot:        [ [5,7] , [1,7] , [1,7] ]
gun_shot_drunk:  [ [2,7] , [4,7] , [1,7] ]
manslaughter:    [1,5] # ACCIDENTAL HEADSHOT (FATAL)

guardian_angel_dies: [1,2]
detective_revealed:  [2,5]